sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc
 
script: curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
<<<<<<< HEAD
after_script: bash release.sh -g 8.1.0
=======
after_script: bash release.sh -g 8.1.5
>>>>>>> Anchor tooltips to bottom right

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
